/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-fixed": "#ffdad4",
        "on-secondary-fixed-variant": "#930100",
        "outline-variant": "#554434",
        "surface-container-high": "#2a2a2a",
        "on-surface-variant": "#dbc2ad",
        "on-background": "#e5e2e1",
        "on-primary-fixed-variant": "#693c00",
        "surface-container-highest": "#353535",
        "primary-fixed-dim": "#ffb86f",
        "surface-variant": "#353535",
        "secondary-fixed-dim": "#ffb4a8",
        "inverse-primary": "#8a5100",
        "surface": "#131313",
        "on-primary-container": "#653a00",
        "on-tertiary-fixed": "#001e2c",
        "on-tertiary-fixed-variant": "#004c69",
        "surface-container": "#20201f",
        "surface-dim": "#131313",
        "inverse-on-surface": "#313030",
        "primary-container": "#ff9900",
        "outline": "#a38d7a",
        "surface-container-lowest": "#0e0e0e",
        "primary": "#ffc082",
        "error": "#ffb4ab",
        "tertiary-container": "#04beff",
        "surface-tint": "#ffb86f",
        "error-container": "#93000a",
        "on-primary-fixed": "#2c1600",
        "primary-fixed": "#ffdcbd",
        "on-secondary": "#690100",
        "on-tertiary": "#00344a",
        "surface-bright": "#393939",
        "background": "#000000", /* Set to pure black as per brand guidance */
        "secondary-container": "#ff5540",
        "tertiary-fixed-dim": "#7cd0ff",
        "inverse-surface": "#e5e2e1",
        "surface-container-low": "#1c1b1b",
        "tertiary": "#8ed5ff",
        "secondary": "#ffb4a8",
        "on-secondary-container": "#5c0000",
        "on-primary": "#4a2800",
        "on-secondary-fixed": "#410000",
        "tertiary-fixed": "#c4e7ff",
        "on-error-container": "#ffdad6",
        "on-tertiary-container": "#004965",
        "on-error": "#690005",
        "on-surface": "#e5e2e1",
        "tangerine": "#FF9900",
        "bright-red": "#FF0000",
        "cotton-white": "#FFFBF5",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px",
        "2xl": "1rem",
        "3xl": "1.5rem"
      },
      spacing: {
        "margin-mobile": "16px",
        "xl": "80px",
        "md": "24px",
        "gutter": "24px",
        "base": "8px",
        "sm": "12px",
        "margin-desktop": "40px",
        "xs": "4px",
        "lg": "48px",
        "2xl": "64px",
        "container-margin": "24px",
        "card-gap": "20px",
        "section-stack": "40px",
      },
      fontFamily: {
        "headline-lg-mobile": ["Montserrat", "sans-serif"],
        "headline-lg": ["Montserrat", "sans-serif"],
        "body-md": ["Montserrat", "sans-serif"],
        "label-sm": ["Montserrat", "sans-serif"],
        "display-lg": ["Montserrat", "sans-serif"],
        "label-bold": ["Montserrat", "sans-serif"],
        "body-lg": ["Montserrat", "sans-serif"],
        "headline-md": ["Montserrat", "sans-serif"]
      },
      fontSize: {
        "headline-lg-mobile": ["32px", { "lineHeight": "1.2", "fontWeight": "800" }],
        "headline-lg": ["40px", { "lineHeight": "1.2", "fontWeight": "800" }],
        "body-md": ["16px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "label-sm": ["12px", { "lineHeight": "1", "fontWeight": "600" }],
        "display-lg": ["64px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "900" }],
        "label-bold": ["14px", { "lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "700" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "500" }],
        "headline-md": ["24px", { "lineHeight": "1.3", "fontWeight": "700" }]
      }
    }
  },
  plugins: [],
}
